<?php
/**
 * Gutenberg block: tejcart-order-tracking/track-order.
 *
 * Server-rendered block (no JS bundle, no asset pipeline) — the editor
 * shows a preview generated by the same render callback the frontend
 * uses, so we don't fork markup. Block attributes mirror the shortcode
 * attributes (title, submit) so authors get the same knobs in either
 * editor.
 *
 * Block-editor toolbar / sidebar UI is intentionally omitted; the
 * default WP block-attribute panel is enough for a two-attribute
 * block. We register the block via PHP only, which keeps us free of
 * the @wordpress/scripts toolchain and the no-Composer-runtime-deps
 * rule (B2) by extension.
 *
 * @package TejCart\Tier2\Order_Tracking\Frontend
 */

declare(strict_types=1);

namespace TejCart\Tier2\Order_Tracking\Frontend;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Block {
    public const NAMESPACE_BLOCK = 'tejcart-order-tracking/track-order';

    private Shortcode $shortcode;

    public function __construct( Shortcode $shortcode ) {
        $this->shortcode = $shortcode;
    }

    public function register(): void {
        add_action( 'init', array( $this, 'register_block' ) );
    }

    public function register_block(): void {
        if ( ! function_exists( 'register_block_type' ) ) {
            return;
        }
        register_block_type(
            self::NAMESPACE_BLOCK,
            array(
                'api_version'     => 3,
                'title'           => __( 'Order Tracking', 'tejcart' ),
                'description'     => __( 'A "Track my order" form for customers.', 'tejcart' ),
                'category'        => 'widgets',
                'icon'            => 'location',
                'keywords'        => array( 'tracking', 'shipment', 'tejcart' ),
                'supports'        => array(
                    'html'   => false,
                    'align'  => array( 'wide', 'full' ),
                    'spacing' => array( 'margin' => true, 'padding' => true ),
                ),
                'attributes'      => array(
                    'title'  => array(
                        'type'    => 'string',
                        'default' => __( 'Track your order', 'tejcart' ),
                    ),
                    'submit' => array(
                        'type'    => 'string',
                        'default' => __( 'Track', 'tejcart' ),
                    ),
                ),
                'render_callback' => array( $this, 'render' ),
            )
        );
    }

    /**
     * @param array<string, mixed> $attrs
     */
    public function render( $attrs = array() ): string {
        if ( ! is_array( $attrs ) ) {
            $attrs = array();
        }
        return $this->shortcode->render( array(
            'title'  => isset( $attrs['title'] )  ? (string) $attrs['title']  : '',
            'submit' => isset( $attrs['submit'] ) ? (string) $attrs['submit'] : '',
        ) );
    }
}
