<?php
/**
 * Customer self-service GDPR data-export request handler.
 *
 * Audit #93 / 09 F-014 — the account dashboard already exposes a
 * "Delete my account" button (Article 17 — Right to Erasure). The
 * matching Article 20 — Right to Data Portability path required the
 * site admin to manually create a request from Tools → Export Personal
 * Data. This class wires a self-service button on the account-details
 * template that pipes the logged-in customer's email through
 * `wp_create_user_request()` and emits the confirmation email so the
 * download link reaches the data subject.
 *
 * @package TejCart\Customer
 */

declare( strict_types=1 );

namespace TejCart\Customer;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Handle the "Download my data" POST from the account-details template.
 */
class Data_Export_Request {
    /**
     * Transient key for surfacing the result of the request to the next page load.
     */
    const NOTICE_TRANSIENT = 'tejcart_data_export_notice_';

    /**
     * Per-user rate limit between consecutive requests (in seconds).
     */
    const REQUEST_INTERVAL = 600;

    /**
     * Wire into the template_redirect lifecycle so we run before output.
     */
    public function init(): void {
        add_action( 'template_redirect', array( $this, 'maybe_handle' ) );
    }

    /**
     * Inspect the current request for a valid export-request submission.
     * Verify the nonce, capture the user's email, and call into core's
     * `wp_create_user_request()` which queues + emails the confirmation
     * link. The download zip is generated by the same exporter callbacks
     * we register in `Data_Exporter`.
     */
    public function maybe_handle(): void {
        if ( empty( $_POST['tejcart_request_data_export'] ) ) {
            return;
        }

        if ( ! is_user_logged_in() ) {
            return;
        }

        $nonce = isset( $_POST['tejcart_data_export_nonce'] )
            ? sanitize_text_field( wp_unslash( $_POST['tejcart_data_export_nonce'] ) )
            : '';
        if ( ! wp_verify_nonce( $nonce, 'tejcart_request_data_export' ) ) {
            $this->store_notice( __( 'Security check failed, please reload and try again.', 'tejcart' ), 'error' );
            return;
        }

        $user = wp_get_current_user();
        if ( ! $user || 0 === (int) $user->ID ) {
            return;
        }

        $email = (string) $user->user_email;
        if ( '' === $email || ! is_email( $email ) ) {
            $this->store_notice( __( 'Your account has no email address on file. Please update it before requesting a data export.', 'tejcart' ), 'error' );
            return;
        }

        // Light rate-limit: one request per user per 10 minutes. The WP
        // core privacy tool will accept multiple but the confirmation
        // email storm is hostile to users and may trip mailbox spam
        // filters. The transient is cleared by the success path below
        // and on consume_notice() so a successful request doesn't lock
        // the user out of trying again later.
        $rate_key = 'tejcart_data_export_rl_' . (int) $user->ID;
        if ( get_transient( $rate_key ) ) {
            $this->store_notice( __( 'A data export was requested recently. Please check your inbox or try again shortly.', 'tejcart' ), 'info' );
            return;
        }

        // Audit M-38 (Product F-014): per-IP rate limit so coordinated
        // abuse via multiple stolen accounts can't spam confirmations.
        if ( class_exists( '\\TejCart\\Security\\Rate_Limiter' ) ) {
            $ip = \TejCart\Security\Rate_Limiter::get_client_ip();
            if ( \TejCart\Security\Rate_Limiter::check_and_record( 'data_export', $ip, 5, 3600 ) ) {
                $this->store_notice( __( 'Too many export requests from your location. Please try again later.', 'tejcart' ), 'error' );
                return;
            }
        }

        if ( ! function_exists( 'wp_create_user_request' ) ) {
            require_once ABSPATH . 'wp-admin/includes/user.php';
        }

        $request_id = wp_create_user_request( $email, 'export_personal_data' );
        if ( is_wp_error( $request_id ) ) {
            $this->store_notice( $request_id->get_error_message(), 'error' );
            return;
        }

        set_transient( $rate_key, 1, self::REQUEST_INTERVAL );

        // Trigger the confirmation email so the link reaches the data
        // subject (the same flow Tools → Export Personal Data uses).
        if ( function_exists( 'wp_send_user_request' ) ) {
            $sent = wp_send_user_request( $request_id );
            if ( is_wp_error( $sent ) ) {
                $this->store_notice( $sent->get_error_message(), 'error' );
                return;
            }
        }

        /**
         * Fires after a customer has requested their personal-data
         * export from the account-details page.
         *
         * @since 1.0.0
         *
         * @param int    $request_id WordPress user_request post ID.
         * @param int    $user_id    User who initiated the request.
         * @param string $email      Email address used for the request.
         */
        do_action( 'tejcart_data_export_requested', (int) $request_id, (int) $user->ID, $email );

        $this->store_notice(
            __( "We've emailed you a confirmation link. Click it to start the data export — the download link arrives by email once the export is ready.", 'tejcart' ),
            'success'
        );

        $redirect = add_query_arg( 'tab', 'account-details', wp_get_referer() ?: home_url( '/' ) );
        wp_safe_redirect( $redirect );
        exit;
    }

    /**
     * Stash a one-off notice for the next request.
     */
    private function store_notice( string $message, string $type ): void {
        set_transient(
            self::NOTICE_TRANSIENT . get_current_user_id(),
            array(
                'message' => $message,
                'type'    => in_array( $type, array( 'success', 'error', 'info' ), true ) ? $type : 'info',
            ),
            60
        );
    }

    /**
     * Read and clear the notice for the current user. Mirrors
     * `Account_Details::consume_notice()` so the account-details
     * template can render both with the same UI.
     *
     * @return array{message:string,type:string}|null
     */
    public static function consume_notice(): ?array {
        $user_id = get_current_user_id();
        if ( ! $user_id ) {
            return null;
        }

        $notice = get_transient( self::NOTICE_TRANSIENT . $user_id );
        if ( ! $notice ) {
            return null;
        }

        delete_transient( self::NOTICE_TRANSIENT . $user_id );
        return is_array( $notice ) ? $notice : null;
    }
}
